<a href="https://colab.research.google.com/github/priyanka36/DailyCodingChallenge/blob/master/sympy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm',disable=['ner','textcat'])

en_core_web_sm is a small English pipeline trained on written web text (blogs, news, comments), that includes vocabulary, syntax and entities.

In [ ]:
text = "This is a simple sentence"
doc = nlp(text)

In [ ]:
type(doc)

spacy.tokens.doc.Doc

We all know that sentences are made up of words belonging to different Parts of Speech (POS). There are eight different POS in the English language: noun, pronoun, verb, adjective, adverb, preposition, conjunction, and intersection.

The POS determines how a specific word functions in meaning in a given sentence. For example, take the word “right”. In the sentence, “The boy was awarded chocolate for giving the right answer”, “right” is used as an adjective. Whereas, in the sentence, “You have the right to say whatever you want”, “right” is treated as a noun.

This goes to show that the POS tag of a word carries a lot of significance when it comes to understanding the meaning of a sentence. And we can leverage it to extract meaningful information from our text.

Let’s take an example to understand this. We’ll be using the popular spaCy library here.

In [ ]:
for token in doc :
  print(token.text,'-->',token.pos_)

This --> DET
is --> AUX
a --> DET
simple --> ADJ
sentence --> NOUN


It was that easy to extract words based on their POS tags. But sometimes extracting information purely based on the POS tags is not enough. Have a look at the sentence below:

If I wanted to extract the subject and the object from a sentence, I can’t do that based on their POS tags. For that, I need to look at how these words are related to each other. These are called Dependencies.

We can make use of spaCy’s displacy visualizer that displays the word dependencies in a graphical manner:

In [ ]:
from spacy import displacy

displacy.render(doc, style='dep',jupyter=True)


The arrows carry a lot of significance here:

The arrowhead points to the words that are dependent on the word pointed by the origin of the arrow
The former is referred to as the child node of the latter. For example, simple is the child node of "sentence"
The word which has no incoming arrow is called the root node of the sentence

In [ ]:
for token in doc:
    # extract subject
    if (token.dep_=='nsubj'):
        print(token.text)
    # extract object
    elif (token.dep_=='dobj'):
        print(token.text)

This


In [ ]:
! wget https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0TJX8Y 

--2022-01-05 10:16:43--  https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0TJX8Y
Resolving dataverse.harvard.edu (dataverse.harvard.edu)... 107.20.115.215, 18.214.187.245, 52.70.216.144
Connecting to dataverse.harvard.edu (dataverse.harvard.edu)|107.20.115.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.1’

dataset.xhtml?persi     [  <=>               ] 212.37K   391KB/s    in 0.5s    

2022-01-05 10:16:46 (391 KB/s) - ‘dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.1’ saved [217467]



In [ ]:
! wget https://github.com/sjankin/UnitedNations/tree/master/files 

--2022-01-05 10:18:34--  https://github.com/sjankin/UnitedNations/tree/master/files
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘files’

files                   [ <=>                ] 140.92K  --.-KB/s    in 0.1s    

2022-01-05 10:18:35 (1.24 MB/s) - ‘files’ saved [144298]



In [ ]:
! unzip /content/dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.1

Archive:  /content/dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.1
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /content/dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.1 or
        /content/dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.1.zip, and cannot find /content/dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.1.ZIP, period.

No zipfiles found.


In [ ]:

! wget https://dataverse.harvard.edu/api/access/datafile/4590189


--2022-01-05 11:58:50--  https://dataverse.harvard.edu/api/access/datafile/4590189
Resolving dataverse.harvard.edu (dataverse.harvard.edu)... 52.70.216.144, 18.214.187.245, 107.20.115.215
Connecting to dataverse.harvard.edu (dataverse.harvard.edu)|52.70.216.144|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://dvn-cloud.s3.amazonaws.com/10.7910/DVN/0TJX8Y/17908980041-241425935a71?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27UNGDC_1970-2020.tar.gz&response-content-type=application%2Fx-gzip&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220105T115851Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=AKIAIEJ3NV7UYCSRJC7A%2F20220105%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=2b5f12ee1ee12b38fff34e0c7a9ad8059add4d1e297ef9083ce6e14d9551ee7a [following]
--2022-01-05 11:58:51--  https://dvn-cloud.s3.amazonaws.com/10.7910/DVN/0TJX8Y/17908980041-241425935a71?response-content-disposition=attachment%3B%20filename%2A%

In [ ]:
import glob
folders = glob.glob('./UNGD/UNGDC 1970-2018/Converted sessions/Session*')

In [ ]:
folders = glob.glob('./UNGD/UNGDC 1970-2018/Converted sessions/Session*')

In [ ]:
folders

[]

In [ ]:
import pandas as pd
df = pd.DataFrame(columns={'Country','Speech','Session','Year'})

In [ ]:
df

Empty DataFrame
Columns: [Country, Year, Speech, Session]
Index: []

In [ ]:
i = 0 
for file in folders:
  print(file)

NameError: ignored

In [ ]:
! wget https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0TJX8Y#

--2022-01-05 13:25:46--  https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0TJX8Y
Resolving dataverse.harvard.edu (dataverse.harvard.edu)... 52.70.216.144, 107.20.115.215, 18.214.187.245
Connecting to dataverse.harvard.edu (dataverse.harvard.edu)|52.70.216.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.4’

dataset.xhtml?persi     [   <=>              ] 212.37K   294KB/s    in 0.7s    

2022-01-05 13:25:48 (294 KB/s) - ‘dataset.xhtml?persistentId=doi:10.7910%2FDVN%2F0TJX8Y.4’ saved [217463]



In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import re

In [ ]:
! wget https://dataverse.harvard.edu/api/access/datafile/4590189


--2022-01-05 13:40:21--  https://dataverse.harvard.edu/api/access/datafile/4590189
Resolving dataverse.harvard.edu (dataverse.harvard.edu)... 52.70.216.144, 18.214.187.245, 107.20.115.215
Connecting to dataverse.harvard.edu (dataverse.harvard.edu)|52.70.216.144|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://dvn-cloud.s3.amazonaws.com/10.7910/DVN/0TJX8Y/17908980041-241425935a71?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27UNGDC_1970-2020.tar.gz&response-content-type=application%2Fx-gzip&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220105T134022Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=AKIAIEJ3NV7UYCSRJC7A%2F20220105%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=ed126897f91b9c93cb6ac399f9ae1ea256af7c305d8df32f7941cfd6f4a9fcba [following]
--2022-01-05 13:40:22--  https://dvn-cloud.s3.amazonaws.com/10.7910/DVN/0TJX8Y/17908980041-241425935a71?response-content-disposition=attachment%3B%20filename%2A%

UnicodeDecodeError: ignored

In [3]:
import numpy as np
data = [[ 11, 0, 21], [0, 19, 18]]
print(data)
nonZeroIndices = np.argwhere(data)
print(nonZeroIndices)

[[11, 0, 21], [0, 19, 18]]
[[0 0]
 [0 2]
 [1 1]
 [1 2]]


In [4]:
data = np.arange(8).reshape(2, 4)
print(data)

[[0 1 2 3]
 [4 5 6 7]]


In [5]:
nonZeroIndices = np.argwhere(data > 4)

In [6]:
nonZeroIndices

array([[1, 1],
       [1, 2],
       [1, 3]])

In [7]:
print('The indices of the elements that are > 4')
print(nonZeroIndices)

The indices of the elements that are > 4
[[1 1]
 [1 2]
 [1 3]]


In [12]:
items = [(5,4),(7,8)]

In [13]:
for item in items:
  print(item)

(5, 4)
(7, 8)


In [17]:
similar_indices = [(135, 121), (135, 122), (135, 123), (135, 124), (135, 125), (135, 126), (135, 127), (135, 128), (135, 129), (135, 130), (135, 131), (135, 132), (135, 133), (135, 134)]


In [18]:
for tpl in similar_indices:
  for item in tpl:
    print(item)

135
121
135
122
135
123
135
124
135
125
135
126
135
127
135
128
135
129
135
130
135
131
135
132
135
133
135
134


In [20]:
import pandas as pd 
idx = pd.Index([1,2,3])

In [21]:
idx

Int64Index([1, 2, 3], dtype='int64')

In [22]:
idx.isin([1, 4])

array([ True, False, False])

In [23]:
from sympy import *

In [24]:
Matrix([[1, -1], [3, 4], [0, 2]])

Matrix([
[1, -1],
[3,  4],
[0,  2]])

In [25]:
M = Matrix([[1, 2, 3], [3, 2, 1]])
N = Matrix([0, 1, 1])

In [26]:
M*N

Matrix([
[5],
[3]])

In [29]:
import sympy as sympy

s = sympy.matrices.Matrix(M)

In [30]:
s

Matrix([
[1, 2, 3],
[3, 2, 1]])

In [31]:
m, similar_indices = s.rref()

In [32]:
m

Matrix([
[1, 0, -1],
[0, 1,  2]])

In [33]:
from sympy import * 
  
M = Matrix([[14, 0, 11, 3], [22, 23, 4, 7], [-12, -34, -3, -4]])
print("Matrix : {} ".format(M))
   
# Use sympy.rref() method 
M_rref = M.rref()  
      
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))  

Matrix : Matrix([[14, 0, 11, 3], [22, 23, 4, 7], [-12, -34, -3, -4]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, 0, 1405/4254],
[0, 1, 0,    10/709],
[0, 0, 1, -314/2127]]), (0, 1, 2))


In [34]:
print(M_rref)

(Matrix([
[1, 0, 0, 1405/4254],
[0, 1, 0,    10/709],
[0, 0, 1, -314/2127]]), (0, 1, 2))


In [35]:
M = Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]])
print("Matrix : {} ".format(M))
   
# Use sympy.rref() method 
M_rref = M.rref()  
      
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))  

Matrix : Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0,   1,   3],
[0, 1, 2/3, 1/3],
[0, 0,   0,   0]]), (0, 1))
